"""Ready-made regions files, one per tool format, for every BAM dataset.

Coordinate-based tools (HipSTR, GangSTR, STRsearch, and most of what will
come) each want the loci to genotype in a file of their own shape. Asking a
submitter for it was the single biggest reason a trial could not run: HipSTR
publishes a 590-locus genome-wide file that is too big for a slice and for the
runner, GangSTR's examples are medical-repeat loci, most tools ship none.

This writes, for each dataset that has a supported-loci panel, the same 24 (or
14) forensic loci in every format STRhub knows how to write:

  regions/hipstr.bed      chrom start end period ref_copies NAME motif   (HipSTR, 7 cols)
  regions/gangstr.bed     chrom start end period motif                   (GangSTR, 5 cols)
  regions/strsearch.bed   the 11-column STRsearch layout with flanks      (STRsearch)
  regions/bed4.bed        chrom start end NAME                            (anything BED-like)

All from datasets/<type>/str_candidates.bed, restricted to the loci the panel
guarantees coverage for (loci.bed), with the motif and flanks read out of hg38
at the tract. Committed, so a run needs no genome to pick one up; regenerate
here when the candidates or the panel change.

Usage:  python harness/build_regions_library.py [--hg38 PATH] [--type illumina-bam-hg38] [--check]
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

ROOT = pathlib.Path(__file__).resolve().parent.parent
HG38_DEFAULT = os.environ.get("STRHUB_HG38", str(pathlib.Path.home() / "genomes" / "hg38" / "hg38.fa"))
FORMATS = ("hipstr", "gangstr", "strsearch", "bed4")

# STRsearch extraction window (see build_strsearch_bed.py for the measurement
# behind it) and flank length.
STRSEARCH_PAD = 300
FLANK = 15


def faidx(hg38: str, region: str) -> str:
    out = subprocess.run(["samtools", "faidx", hg38, region], capture_output=True, text=True, check=True).stdout
    return "".join(out.splitlines()[1:]).upper()


def dominant_motif(tract: str, period: int) -> str:
    counts = collections.Counter(tract[i:i + period] for i in range(len(tract) - period + 1))
    return counts.most_common(1)[0][0]


def read_candidates(path: pathlib.Path) -> list[dict]:
    rows = []
    for ln in path.read_text().splitlines():
        if not ln.strip() or ln.startswith("#"):
            continue
        f = ln.split("\t")
        rows.append({"chrom": f[0], "start": int(f[1]), "end": int(f[2]), "period": int(f[3]),
                     "ref_copies": f[4], "name": f[5], "motif": f[6] if len(f) > 6 else "N/A"})
    return rows


def panel_names(path: pathlib.Path) -> set[str]:
    names = set()
    for ln in path.read_text().splitlines():
        if ln.strip() and not ln.startswith("#"):
            names.add(ln.split("\t")[3])
    return names


def build(dataset: str, hg38: str) -> dict[str, str]:
    d = ROOT / "datasets" / dataset
    cands = read_candidates(d / "str_candidates.bed")
    keep = panel_names(d / "loci.bed")
    # A panel entry can group several candidate tracts: the Y panel lists
    # "DYS389I/DYS389II" and "DYS448" for the candidates DYS389I, DYS389II.1,
    # DYS389II.2, DYS448.1 and DYS448.2. A candidate belongs if its name, or its
    # name before a ".", is one of the names a panel entry carries.
    panel_parts = {part for name in keep for part in name.split("/")}
    def in_panel(c):
        base = c["name"].split(".")[0]
        return c["name"] in keep or base in keep or base in panel_parts
    rows = [c for c in cands if in_panel(c)]
    covered = {c["name"] for c in rows} | {c["name"].split(".")[0] for c in rows}
    # A panel name is covered when it appears whole ("DYS19/DYS394" is one locus
    # with two names) or when any of the names it groups does.
    missing = [name for name in keep
               if name not in covered and not any(part in covered for part in name.split("/"))]
    if missing:
        raise SystemExit(f"{dataset}: panel loci without a candidate: {sorted(missing)}")

    for c in rows:
        tract = faidx(hg38, f"{c['chrom']}:{c['start']}-{c['end']}")
        c["motif_seq"] = dominant_motif(tract, c["period"]) if c["motif"] in ("N/A", "") else c["motif"]
        c["left"] = faidx(hg38, f"{c['chrom']}:{c['start'] - FLANK}-{c['start'] - 1}")
        c["right"] = faidx(hg38, f"{c['chrom']}:{c['end'] + 1}-{c['end'] + FLANK}")

    hdr = (f"# STRhub Verified regions library, {dataset}: {len(rows)} forensic STR loci the reference "
           f"slice covers (datasets/{dataset}/loci.bed). hg38. Generated by harness/build_regions_library.py; "
           "do not edit by hand.\n")
    out = {}
    out["hipstr"] = hdr + "".join(
        f"{c['chrom']}\t{c['start']}\t{c['end']}\t{c['period']}\t{c['ref_copies']}\t{c['name']}\t{c['motif_seq']}\n" for c in rows)
    out["gangstr"] = hdr + "".join(
        f"{c['chrom']}\t{c['start']}\t{c['end']}\t{c['period']}\t{c['motif_seq']}\n" for c in rows)
    out["bed4"] = hdr + "".join(f"{c['chrom']}\t{c['start']}\t{c['end']}\t{c['name']}\n" for c in rows)
    ss_header = ("#Chr\tStart\tEnd\tPeriod\tReference allele\tMarker\tOfficial name\t"
                 "STR sequence structure\tStrand\t5' Flanking sequence\t3' Flanking sequence\n")
    out["strsearch"] = ss_header + "".join(
        f"{c['chrom']}\t{c['start'] - STRSEARCH_PAD}\t{c['end'] + STRSEARCH_PAD}\t{c['period']}\t{c['ref_copies']}\t"
        f"{c['name']}\t{c['name']}\t[{c['motif_seq']}]n\t+\t{c['left']}\t{c['right']}\n" for c in rows)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hg38", default=HG38_DEFAULT)
    ap.add_argument("--type", action="append", help="dataset type(s); default: every dataset with a panel")
    ap.add_argument("--check", action="store_true", help="fail if the committed files differ")
    args = ap.parse_args()
    if not pathlib.Path(args.hg38).exists():
        raise SystemExit(f"hg38 FASTA not found at {args.hg38}; pass --hg38 or set STRHUB_HG38")
    index = json.loads((ROOT / "datasets" / "index.json").read_text())
    types = args.type or [k for k, v in index["datasets"].items() if v.get("supported_loci")]
    drift = []
    for ds in types:
        files = build(ds, args.hg38)
        outdir = ROOT / "datasets" / ds / "regions"
        outdir.mkdir(exist_ok=True)
        for fmt, text in files.items():
            p = outdir / f"{fmt}.bed"
            if args.check:
                if not p.exists() or p.read_text() != text:
                    drift.append(str(p.relative_to(ROOT)))
            else:
                p.write_text(text)
                print(f"wrote {p.relative_to(ROOT)} ({text.count(chr(10)) - 1} loci)")
    if args.check:
        if drift:
            print("regions library is stale:", *drift, sep="\n  ")
            return 1
        print("regions library up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
